/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appmedicale;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class gestionpaiement extends javax.swing.JFrame {

    /**
     * Creates new form gestionpaiement
     */
    public gestionpaiement() {
        initComponents();
        
        
    }
    
private void calculerStatistiques() {
    // Utiliser le modèle de jTable2
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    
    int total = model.getRowCount();
    int payes = 0;
    int impayes = 0;
    double montantTotal = 0;
    
    for (int i = 0; i < total; i++) {
        String statut = (String) model.getValueAt(i, 6);  // Colonne 6 = Statut
        double prix = Double.parseDouble(((String) model.getValueAt(i, 5)).replace(" DH", ""));  // Colonne 5 = Prix
        
        if ("Payé".equals(statut)) {
            payes++;
        } else {
            impayes++;
        }
        montantTotal += prix;
    }
    
    System.out.println("Statistiques - Total: " + total + ", Payés: " + payes + 
                      ", Impayés: " + impayes + ", Montant: " + montantTotal + " DH");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "patient", "telephone", "categorie", "prix", "description"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 510, 280));

        jButton1.setBackground(new java.awt.Color(31, 153, 88));
        jButton1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("lister");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 160, 30));

        jButton2.setBackground(new java.awt.Color(31, 153, 88));
        jButton2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("valider paiement");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 160, 30));

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 153, 88));
        jLabel2.setText("gestion des paiements");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 270, 40));

        jButton3.setBackground(new java.awt.Color(31, 153, 88));
        jButton3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("fermer");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 160, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 880, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    try {
        
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez sélectionner une consultation", 
                "Aucune sélection", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
      DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    

        int idConsultation = (int) model.getValueAt(selectedRow, 0);
        String nomPatient = (String) model.getValueAt(selectedRow, 2);
        double prix = Double.parseDouble(((String) model.getValueAt(selectedRow, 5)).replace(" DH", ""));

        int confirmation = JOptionPane.showConfirmDialog(this,
            "Marquer la consultation comme PAYÉE ?\n\n" +
            "Patient: " + nomPatient + "\n" +
            "Montant: " + prix + " DH\n\n" +
            "Un reçu PDF sera généré automatiquement.",
            "Confirmation de paiement",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (confirmation == JOptionPane.YES_OPTION) {
            // Mettre à jour le statut dans la base de données
            ConsultationDAO consultationDAO = new ConsultationDAO();
            boolean succes = consultationDAO.mettreAJourStatutPaiement(idConsultation, "Payé");

            if (succes) {
                // Mettre à jour l'affichage dans la table
                model.setValueAt("Payé", selectedRow, 6);

                // ✅ GÉNÉRATION DU PDF DIRECTEMENT ICI
                try {
                    // Récupérer les détails complets de la consultation
                    Consultation consultation = consultationDAO.trouverParId(idConsultation);
                    
                    if (consultation != null) {
                        // Créer le nom du fichier
                        String nomFichier = "Recu_Paiement_" + consultation.getPatient().getNom().replace(" ", "_") + 
                                           "_" + new java.text.SimpleDateFormat("yyyyMMdd_HHmm").format(new java.util.Date()) + ".pdf";
                        
                        // Chemin sur le bureau
                        String cheminBureau = System.getProperty("user.home") + "/Desktop/";
                        String cheminComplet = cheminBureau + nomFichier;
                        
                        // ✅ CRÉATION DU PDF
                        com.itextpdf.text.Document document = new com.itextpdf.text.Document();
                        com.itextpdf.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream(cheminComplet));
                        document.open();
                        
                        // EN-TÊTE
                        com.itextpdf.text.Font titreFont = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 18, com.itextpdf.text.Font.BOLD, com.itextpdf.text.BaseColor.BLUE);
                        com.itextpdf.text.Paragraph titre = new com.itextpdf.text.Paragraph("REÇU DE PAIEMENT", titreFont);
                        titre.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                        document.add(titre);
                        
                        document.add(new com.itextpdf.text.Paragraph(" "));
                        document.add(new com.itextpdf.text.Paragraph("_________________________________________________________"));
                        document.add(new com.itextpdf.text.Paragraph(" "));
                        
                        // CABINET MÉDICAL
                        com.itextpdf.text.pdf.PdfPTable tableCabinet = new com.itextpdf.text.pdf.PdfPTable(2);
                        tableCabinet.setWidthPercentage(100);
                        
                        com.itextpdf.text.pdf.PdfPCell cellCabinet = new com.itextpdf.text.pdf.PdfPCell(new com.itextpdf.text.Phrase("CABINET MÉDICAL", 
                            new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 12, com.itextpdf.text.Font.BOLD)));
                        cellCabinet.setColspan(2);
                        cellCabinet.setHorizontalAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                        cellCabinet.setBackgroundColor(com.itextpdf.text.BaseColor.LIGHT_GRAY);
                        cellCabinet.setPadding(8);
                        tableCabinet.addCell(cellCabinet);
                        
                        tableCabinet.addCell(new com.itextpdf.text.Phrase("Adresse:", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        tableCabinet.addCell(new com.itextpdf.text.Phrase("123 Rue de la Santé, 75000 Rabat", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        
                        tableCabinet.addCell(new com.itextpdf.text.Phrase("Téléphone:", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        tableCabinet.addCell(new com.itextpdf.text.Phrase("01 23 45 67 89", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        
                        document.add(tableCabinet);
                        document.add(new com.itextpdf.text.Paragraph(" "));
                        
                        // INFORMATIONS PATIENT
                        com.itextpdf.text.pdf.PdfPTable tablePatient = new com.itextpdf.text.pdf.PdfPTable(2);
                        tablePatient.setWidthPercentage(100);
                        
                        com.itextpdf.text.pdf.PdfPCell cellPatient = new com.itextpdf.text.pdf.PdfPCell(new com.itextpdf.text.Phrase("INFORMATIONS PATIENT", 
                            new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 12, com.itextpdf.text.Font.BOLD)));
                        cellPatient.setColspan(2);
                        cellPatient.setHorizontalAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                        cellPatient.setBackgroundColor(new com.itextpdf.text.BaseColor(200, 200, 255));
                        cellPatient.setPadding(8);
                        tablePatient.addCell(cellPatient);
                        
                        tablePatient.addCell(new com.itextpdf.text.Phrase("Nom:", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        tablePatient.addCell(new com.itextpdf.text.Phrase(consultation.getPatient().getNom(), new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        
                        tablePatient.addCell(new com.itextpdf.text.Phrase("Téléphone:", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        tablePatient.addCell(new com.itextpdf.text.Phrase(consultation.getPatient().getTelephone(), new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        
                        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy à HH:mm");
                        tablePatient.addCell(new com.itextpdf.text.Phrase("Date consultation:", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        tablePatient.addCell(new com.itextpdf.text.Phrase(sdf.format(consultation.getDateConsultation()), new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        
                        tablePatient.addCell(new com.itextpdf.text.Phrase("Type:", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        tablePatient.addCell(new com.itextpdf.text.Phrase(consultation.getCategorie().getDesignation(), new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        
                        document.add(tablePatient);
                        document.add(new com.itextpdf.text.Paragraph(" "));
                        
                        // DÉTAILS PAIEMENT
                        com.itextpdf.text.pdf.PdfPTable tablePaiement = new com.itextpdf.text.pdf.PdfPTable(2);
                        tablePaiement.setWidthPercentage(100);
                        
                        com.itextpdf.text.pdf.PdfPCell cellPaiement = new com.itextpdf.text.pdf.PdfPCell(new com.itextpdf.text.Phrase("DÉTAILS DU PAIEMENT", 
                            new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 12, com.itextpdf.text.Font.BOLD)));
                        cellPaiement.setColspan(2);
                        cellPaiement.setHorizontalAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                        cellPaiement.setBackgroundColor(new com.itextpdf.text.BaseColor(255, 200, 200));
                        cellPaiement.setPadding(8);
                        tablePaiement.addCell(cellPaiement);
                        
                        tablePaiement.addCell(new com.itextpdf.text.Phrase("Montant payé:", 
                            new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10, com.itextpdf.text.Font.BOLD)));
                        tablePaiement.addCell(new com.itextpdf.text.Phrase(String.format("%.2f DH", consultation.getPrix()), 
                            new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 12, com.itextpdf.text.Font.BOLD, com.itextpdf.text.BaseColor.RED)));
                        
                        tablePaiement.addCell(new com.itextpdf.text.Phrase("Statut:", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        com.itextpdf.text.pdf.PdfPCell statutCell = new com.itextpdf.text.pdf.PdfPCell(new com.itextpdf.text.Phrase("PAYÉ", 
                            new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 12, com.itextpdf.text.Font.BOLD, com.itextpdf.text.BaseColor.GREEN)));
                        statutCell.setHorizontalAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                        tablePaiement.addCell(statutCell);
                        
                        tablePaiement.addCell(new com.itextpdf.text.Phrase("Date du paiement:", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        tablePaiement.addCell(new com.itextpdf.text.Phrase(sdf.format(new java.util.Date()), new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        
                        tablePaiement.addCell(new com.itextpdf.text.Phrase("N° du reçu:", new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        tablePaiement.addCell(new com.itextpdf.text.Phrase("RC" + consultation.getId() + "-" + 
                            new java.text.SimpleDateFormat("yyyyMMdd").format(new java.util.Date()), new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10)));
                        
                        document.add(tablePaiement);
                        document.add(new com.itextpdf.text.Paragraph(" "));
                        
                        // MESSAGE DE REMERCIEMENT
                        com.itextpdf.text.Paragraph remerciement = new com.itextpdf.text.Paragraph("Paiement reçu avec succès. Merci de votre confiance!", 
                            new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 11, com.itextpdf.text.Font.ITALIC));
                        remerciement.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                        document.add(remerciement);
                        
                        document.add(new com.itextpdf.text.Paragraph(" "));
                        document.add(new com.itextpdf.text.Paragraph(" "));
                        
                        // PIED DE PAGE
                        com.itextpdf.text.Paragraph pied = new com.itextpdf.text.Paragraph("Ce document fait foi de paiement et doit être conservé.\n" +
                            "Pour toute réclamation, merci de contacter le cabinet sous 30 jours.", 
                            new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 8, com.itextpdf.text.Font.NORMAL, com.itextpdf.text.BaseColor.GRAY));
                        pied.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                        document.add(pied);
                        
                        document.close();

                        // ✅ OUVERTURE AUTOMATIQUE DU PDF
                        if (java.awt.Desktop.isDesktopSupported()) {
                            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
                            java.io.File fichier = new java.io.File(cheminComplet);
                            if (fichier.exists()) {
                                desktop.open(fichier);
                            }
                        }

                        // Message de succès complet
                        JOptionPane.showMessageDialog(this,
                            "✅ Paiement validé avec succès!\n\n" +
                            "• Statut mis à jour: PAYÉ\n" +
                            "• Reçu généré: " + nomFichier + "\n" +
                            "• Emplacement: Bureau\n\n" +
                            "Le reçu PDF s'ouvre automatiquement.",
                            "Paiement confirmé",
                            JOptionPane.INFORMATION_MESSAGE);

                    } else {
                        JOptionPane.showMessageDialog(this,
                            "Consultation non trouvée dans la base de données",
                            "Erreur",
                            JOptionPane.ERROR_MESSAGE);
                    }

                } catch (Exception pdfError) {
                    System.err.println("Erreur génération PDF: " + pdfError.getMessage());
                    pdfError.printStackTrace();
                    
                    // Message de succès même si PDF échoue
                    JOptionPane.showMessageDialog(this,
                        "✅ Paiement validé avec succès!\n\n" +
                        "Le statut a été mis à jour mais le reçu PDF n'a pas pu être généré.\n" +
                        "Erreur: " + pdfError.getMessage(),
                        "Paiement confirmé - Reçu non généré",
                        JOptionPane.WARNING_MESSAGE);
                }

                // Recalculer les statistiques
                calculerStatistiques();

            } else {
                JOptionPane.showMessageDialog(this,
                    "❌ Erreur lors de la mise à jour du statut en base de données",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "❌ Erreur: " + e.getMessage(),
            "Erreur",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try {
        // Récupérer tous les rendez-vous
        ConsultationDAO consultationDAO = new ConsultationDAO();
        java.util.List<Consultation> tousRendezVous = consultationDAO.getToutesConsultations();
        
        // Vider la table
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        
        // Formateur de date
        java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm");
        
        // Ajouter chaque rendez-vous à la table
        for (Consultation rdv : tousRendezVous) {
            Object[] row = {
                rdv.getId(),
                dateFormat.format(rdv.getDateConsultation()),
                rdv.getPatient().getNom(),
                rdv.getPatient().getTelephone(),
                rdv.getCategorie().getDesignation(),
                rdv.getPrix() + " DH",
                rdv.getDescription(),
                rdv.getStatutPaiement() != null ? rdv.getStatutPaiement() : "Impayé"
            };
            model.addRow(row);
        }
        
        // Message de confirmation
        JOptionPane.showMessageDialog(this,
            tousRendezVous.size() + " rendez-vous chargés avec succès!",
            "Chargement réussi",
            JOptionPane.INFORMATION_MESSAGE);
            
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Erreur lors du chargement: " + e.getMessage(),
            "Erreur",
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         this.dispose();
         new DashboardAssistante().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionpaiement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionpaiement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionpaiement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionpaiement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionpaiement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
