/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appmedicale;

import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.*;
/**
 *
 * @author HP
 */
public class gestionRdv extends javax.swing.JFrame {
    
   
    /**
     * Creates new form gestionRdv
     */
    public gestionRdv() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 153, 88));
        jLabel1.setText("gestion de rendez-cabinet medical");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 380, -1));

        jLabel2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 153, 88));
        jLabel2.setText("recherche patient :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel3.setText("Date  :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 60, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 110, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "patient", "telephone", "categorie", "prix", "description"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 570, 310));

        jButton1.setBackground(new java.awt.Color(31, 153, 88));
        jButton1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ajouter");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 90, -1));

        jButton2.setBackground(new java.awt.Color(31, 153, 88));
        jButton2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("modifier");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 80, -1));

        jButton3.setBackground(new java.awt.Color(31, 153, 88));
        jButton3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("supprimer");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 90, -1));

        jButton4.setBackground(new java.awt.Color(31, 153, 88));
        jButton4.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("fermer");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 70, -1));

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 153, 88));
        jLabel4.setText("ajout de rendez vous ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 180, -1));

        jLabel5.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel5.setText("patient");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 130, -1));

        jButton5.setBackground(new java.awt.Color(105, 190, 186));
        jButton5.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton5.setText("charger");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 100, -1));

        jLabel6.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel6.setText("date(jj/mm/aaaa)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel7.setText("heure");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 40, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 90, -1));

        jLabel8.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel8.setText("minute");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 50, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel9.setText("categorie");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, -1));

        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 100, -1));

        jLabel10.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel10.setText("prix DH");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 100, -1));

        jLabel11.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel11.setText("description");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 90, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 130, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 170, -1));

        jButton6.setBackground(new java.awt.Color(31, 153, 88));
        jButton6.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("lister par date");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 180, -1));

        jButton7.setBackground(new java.awt.Color(31, 153, 88));
        jButton7.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("lister");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 920, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       this.dispose();
            new DashboardAssistante().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
   
        
      
         
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
try {
    // Créer le DAO et récupérer les patients
    PatientDAO patientDAO = new PatientDAO();
    List<Patient> patients = patientDAO.listerPatients();
    
    // Vider le comboBox
    jComboBox1.removeAllItems();
    
    // Ajouter l'élément de sélection par défaut
    jComboBox1.addItem("-- Sélectionner un patient --");
    
    // Ajouter chaque patient avec nom et téléphone
    for (Patient patient : patients) {
        String affichage = patient.getNom() + " - " + patient.getTelephone();
        jComboBox1.addItem(affichage);
    }
    
    // Forcer le rafraîchissement de l'affichage
    jComboBox1.revalidate();
    jComboBox1.repaint();
    
} catch (Exception e) {
    // En cas d'erreur, afficher un message
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Erreur lors du chargement des patients: " + e.getMessage(),
        "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
}

try {
        // Créer le DAO et récupérer les catégories
        CategorieDAO categorieDAO = new CategorieDAO();
        List<Categorie> categories = categorieDAO.listerCategories();
        
        // Vider le comboBox (remplacez jComboBox2 par le nom de votre JComboBox)
        jComboBox4.removeAllItems();
        
        // Ajouter chaque catégorie
        for (Categorie categorie : categories) {
            jComboBox4.addItem(categorie.getDesignation());
        }
        
        // Forcer le rafraîchissement
        jComboBox4.revalidate();
        jComboBox4.repaint();
        
        // Message de confirmation
        javax.swing.JOptionPane.showMessageDialog(this, 
            categories.size() + " catégories chargées avec succès",
            "Chargement réussi", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
    } catch (Exception e) {
        // En cas d'erreur
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Erreur lors du chargement des catégories: " + e.getMessage(),
            "Erreur", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        // Vérifier qu'un patient est sélectionné
        String patientSelectionne = (String) jComboBox1.getSelectedItem();
        if (patientSelectionne == null || patientSelectionne.equals("-- Sélectionner un patient --")) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez sélectionner un patient", 
                "Patient manquant", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
         // Vérifier qu'une catégorie est sélectionnée
        String categorieSelectionnee = (String) jComboBox4.getSelectedItem();
        if (categorieSelectionnee == null || categorieSelectionnee.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez sélectionner une catégorie", 
                "Catégorie manquante", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
         // Vérifier et parser la date
        String dateText = jTextField5.getText().trim();
        if (dateText.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez saisir une date (jj/mm/aaaa)", 
                "Date manquante", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
         Date dateRendezVous;
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            dateFormat.setLenient(false);
            dateRendezVous = dateFormat.parse(dateText);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Format de date invalide. Utilisez jj/mm/aaaa\nExemple: 25/12/2024", 
                "Date invalide", 
                JOptionPane.WARNING_MESSAGE);
            jTextField5.requestFocus();
            jTextField5.selectAll();
            return;
        }
        
         // Vérifier l'heure
        String heure = (String) jComboBox2.getSelectedItem();
        String minutes = (String) jComboBox3.getSelectedItem();
        if (heure == null || minutes == null) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez sélectionner une heure", 
                "Heure manquante", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
         // Vérifier le prix
        String prixText = jTextField3.getText().trim();
        if (prixText.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez saisir un prix", 
                "Prix manquant", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        double prix;
        try {
            prix = Double.parseDouble(prixText);
            if (prix <= 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez saisir un prix valide (nombre positif)", 
                "Prix invalide", 
                JOptionPane.WARNING_MESSAGE);
            jTextField3.requestFocus();
            jTextField3.selectAll();
            return;
        }
        
        PatientDAO patientDAO = new PatientDAO();
        List<Patient> patients = patientDAO.listerPatients();
        Patient patient = null;
        
        String nomPatient = patientSelectionne.split(" - ")[0];
        for (Patient p : patients) {
            if (p.getNom().equals(nomPatient)) {
                patient = p;
                break;
            }
        }
        
        if (patient == null) {
            JOptionPane.showMessageDialog(this, 
                "Patient non trouvé dans la base de données", 
                "Erreur", 
                JOptionPane.ERROR_MESSAGE);
            return;}
        
         // ✅ RÉCUPÉRATION DIRECTE DE LA CATÉGORIE
        CategorieDAO categorieDAO = new CategorieDAO();
        List<Categorie> categories = categorieDAO.listerCategories();
        Categorie categorie = null;
        
        for (Categorie c : categories) {
            if (c.getDesignation().equals(categorieSelectionnee)) {
                categorie = c;
                break;
            }
        }
        
        if (categorie == null) {
            JOptionPane.showMessageDialog(this, 
                "Catégorie non trouvée dans la base de données", 
                "Erreur", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
          // Combiner date et heure
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.setTime(dateRendezVous);
        cal.set(java.util.Calendar.HOUR_OF_DAY, Integer.parseInt(heure));
        cal.set(java.util.Calendar.MINUTE, Integer.parseInt(minutes));
        cal.set(java.util.Calendar.SECOND, 0);
        
        Date dateTimeComplete = cal.getTime();
        
        // Vérifier si la date n'est pas dans le passé
        if (dateTimeComplete.before(new Date())) {
            int confirmation = JOptionPane.showConfirmDialog(this,
                "La date et l'heure sélectionnées sont dans le passé.\n" +
                "Voulez-vous quand même créer ce rendez-vous?",
                "Date passée", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
                
            if (confirmation != JOptionPane.YES_OPTION) {
                return;
            }
        }

        // Récupérer la description
        String description = jTextField4.getText().trim();
        
         // Créer l'objet Consultation
        Consultation nouveauRendezVous = new Consultation(
            dateTimeComplete, 
            description, 
            prix, 
            patient, 
            categorie
        );
        
         // Confirmation avant ajout
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy 'à' HH'h'mm");
        int confirmation = JOptionPane.showConfirmDialog(this,
            "Confirmer l'ajout du rendez-vous?\n\n" +
            "👤 Patient: " + patient.getNom() + "\n" +
            "📅 Date: " + sdf.format(dateTimeComplete) + "\n" +
            "📋 Catégorie: " + categorie.getDesignation() + "\n" +
            "💰 Prix: " + prix + " DH\n" +
            "📝 Description: " + (description.isEmpty() ? "Aucune" : description),
            "Confirmation d'ajout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        
         if (confirmation == JOptionPane.YES_OPTION) {
            // Ajouter dans la base de données
            ConsultationDAO consultationDAO = new ConsultationDAO();
            boolean succes = consultationDAO.ajouterConsultation(nouveauRendezVous);

            if (succes) {
                JOptionPane.showMessageDialog(this,
                    "✅ Rendez-vous ajouté avec succès!\n\n" +
                    patient.getNom() + " - " + sdf.format(dateTimeComplete),
                    "Succès",
                    JOptionPane.INFORMATION_MESSAGE);
            
            jTextField5.setText("");
            jTextField3.setText("");
            jTextField4.setText("");}
             else {
                JOptionPane.showMessageDialog(this,
                    "❌ Erreur lors de l'ajout du rendez-vous",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
            }
            
            
         
         
         }
        
        
        
         
        
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "❌ Erreur: " + e.getMessage(),
            "Erreur",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         try {
        // Date du jour par défaut si vide
        String dateText = jTextField2.getText().trim();
        if (dateText.isEmpty()) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            jTextField2.setText(dateFormat.format(new Date()));
            dateText = jTextField2.getText();
        }
        
         // Parser la date
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = dateFormat.parse(dateText);
        
         // Récupérer les rendez-vous
        ConsultationDAO dao = new ConsultationDAO();
        List<Consultation> rendezVous = dao.getConsultationsDuJour(date);
        
        // Afficher dans la table
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
         SimpleDateFormat dateHeureFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        for (Consultation rdv : rendezVous) {
            model.addRow(new Object[]{
                rdv.getId(),
                dateHeureFormat.format(rdv.getDateConsultation()),
                rdv.getPatient().getNom(),
                rdv.getPatient().getTelephone(),
                rdv.getCategorie().getDesignation(),
                rdv.getPrix() + " DH",
                rdv.getDescription()
            });
        }
        
         JOptionPane.showMessageDialog(this, 
            rendezVous.size() + " rendez-vous chargés", 
            "Succès", JOptionPane.INFORMATION_MESSAGE);
        
         }catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Erreur: " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    try {
        // Vérifier qu'un rendez-vous est sélectionné dans la table
        int selectedRow = jTable1.getSelectedRow();
       
        // Donner le focus à la table pour s'assurer que la sélection est active
         jTable1.requestFocusInWindow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez sélectionner un rendez-vous à modifier", 
                "Aucune sélection", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Récupérer l'ID du rendez-vous sélectionné
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int idRendezVous = (int) model.getValueAt(selectedRow, 0);

        // Vérifier qu'un patient est sélectionné
        String patientSelectionne = (String) jComboBox1.getSelectedItem();
        if (patientSelectionne == null || patientSelectionne.equals("-- Sélectionner un patient --")) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez sélectionner un patient", 
                "Patient manquant", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Vérifier qu'une catégorie est sélectionnée
        String categorieSelectionnee = (String) jComboBox4.getSelectedItem();
        if (categorieSelectionnee == null || categorieSelectionnee.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez sélectionner une catégorie", 
                "Catégorie manquante", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Vérifier et parser la date
        String dateText = jTextField5.getText().trim();
        if (dateText.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez saisir une date (jj/mm/aaaa)", 
                "Date manquante", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Date dateRendezVous;
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            dateFormat.setLenient(false);
            dateRendezVous = dateFormat.parse(dateText);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Format de date invalide. Utilisez jj/mm/aaaa\nExemple: 25/12/2024", 
                "Date invalide", 
                JOptionPane.WARNING_MESSAGE);
            jTextField5.requestFocus();
            jTextField5.selectAll();
            return;
        }
        
        // Vérifier l'heure
        String heure = (String) jComboBox2.getSelectedItem();
        String minutes = (String) jComboBox3.getSelectedItem();
        if (heure == null || minutes == null) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez sélectionner une heure", 
                "Heure manquante", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Vérifier le prix
        String prixText = jTextField3.getText().trim();
        if (prixText.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez saisir un prix", 
                "Prix manquant", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        double prix;
        try {
            prix = Double.parseDouble(prixText);
            if (prix <= 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez saisir un prix valide (nombre positif)", 
                "Prix invalide", 
                JOptionPane.WARNING_MESSAGE);
            jTextField3.requestFocus();
            jTextField3.selectAll();
            return;
        }
        
        // Récupérer le patient
        PatientDAO patientDAO = new PatientDAO();
        List<Patient> patients = patientDAO.listerPatients();
        Patient patient = null;
        
        String nomPatient = patientSelectionne.split(" - ")[0];
        for (Patient p : patients) {
            if (p.getNom().equals(nomPatient)) {
                patient = p;
                break;
            }
        }
        
        if (patient == null) {
            JOptionPane.showMessageDialog(this, 
                "Patient non trouvé dans la base de données", 
                "Erreur", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Récupérer la catégorie
        CategorieDAO categorieDAO = new CategorieDAO();
        List<Categorie> categories = categorieDAO.listerCategories();
        Categorie categorie = null;
        
        for (Categorie c : categories) {
            if (c.getDesignation().equals(categorieSelectionnee)) {
                categorie = c;
                break;
            }
        }
        
        if (categorie == null) {
            JOptionPane.showMessageDialog(this, 
                "Catégorie non trouvée dans la base de données", 
                "Erreur", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Combiner date et heure
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.setTime(dateRendezVous);
        cal.set(java.util.Calendar.HOUR_OF_DAY, Integer.parseInt(heure));
        cal.set(java.util.Calendar.MINUTE, Integer.parseInt(minutes));
        cal.set(java.util.Calendar.SECOND, 0);
        
        Date dateTimeComplete = cal.getTime();
        
        // Vérifier si la date n'est pas dans le passé
        if (dateTimeComplete.before(new Date())) {
            int confirmation = JOptionPane.showConfirmDialog(this,
                "La date et l'heure sélectionnées sont dans le passé.\n" +
                "Voulez-vous quand même modifier ce rendez-vous?",
                "Date passée", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
                
            if (confirmation != JOptionPane.YES_OPTION) {
                return;
            }
        }

        // Récupérer la description
        String description = jTextField4.getText().trim();
        
        // Créer l'objet Consultation modifié
        Consultation rendezVousModifie = new Consultation(
            idRendezVous,
            dateTimeComplete, 
            description, 
            prix, 
            patient, 
            categorie
        );
        
        // Confirmation avant modification
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy 'à' HH'h'mm");
        int confirmation = JOptionPane.showConfirmDialog(this,
            "Confirmer la modification du rendez-vous?\n\n" +
            "👤 Patient: " + patient.getNom() + "\n" +
            "📅 Date: " + sdf.format(dateTimeComplete) + "\n" +
            "📋 Catégorie: " + categorie.getDesignation() + "\n" +
            "💰 Prix: " + prix + " DH\n" +
            "📝 Description: " + (description.isEmpty() ? "Aucune" : description),
            "Confirmation de modification",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        
        if (confirmation == JOptionPane.YES_OPTION) {
            // Modifier dans la base de données
            ConsultationDAO consultationDAO = new ConsultationDAO();
            boolean succes = consultationDAO.modifierConsultation(rendezVousModifie);

            if (succes) {
                JOptionPane.showMessageDialog(this,
                    "✅ Rendez-vous modifié avec succès!\n\n" +
                    patient.getNom() + " - " + sdf.format(dateTimeComplete),
                    "Succès",
                    JOptionPane.INFORMATION_MESSAGE);
            
                // Vider les champs
                jTextField5.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                
                
                
            } else {
                JOptionPane.showMessageDialog(this,
                    "❌ Erreur lors de la modification du rendez-vous",
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "❌ Erreur: " + e.getMessage(),
            "Erreur",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      // Vérifier qu'un rendez-vous est sélectionné dans la table
     int selectedRow = jTable1.getSelectedRow();
     if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, 
        "Veuillez sélectionner un rendez-vous à supprimer", 
        "Aucune sélection", 
        JOptionPane.WARNING_MESSAGE);
    return;
}

// Récupérer l'ID de la consultation depuis la table
    int idConsultation = (int) jTable1.getValueAt(selectedRow, 0);

// Demander confirmation avant suppression
   int confirmation = JOptionPane.showConfirmDialog(this,
    "Êtes-vous sûr de vouloir supprimer cette consultation ?",
    "Confirmation de suppression",
    JOptionPane.YES_NO_OPTION);

   if (confirmation != JOptionPane.YES_OPTION) {
    return;
}

// Utiliser le DAO pour supprimer
  ConsultationDAO consultationDAO = new ConsultationDAO();

  if (consultationDAO.supprimerConsultation(idConsultation)) {
    JOptionPane.showMessageDialog(this,
        "Consultation supprimée avec succès",
        "Suppression réussie",
        JOptionPane.INFORMATION_MESSAGE);
    
    
  } else {
    JOptionPane.showMessageDialog(this,
        "Erreur lors de la suppression de la consultation",
        "Erreur",
        JOptionPane.ERROR_MESSAGE);
}    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
        // Récupérer tous les rendez-vous de la base de données
        ConsultationDAO consultationDAO = new ConsultationDAO();
        java.util.List<Consultation> tousRendezVous = consultationDAO.getToutesConsultations();
        
        // Vider la table
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        // Formateur de date
        java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm");
        
        // Ajouter chaque rendez-vous à la table
        for (Consultation rdv : tousRendezVous) {
            Object[] row = {
                rdv.getId(),
                dateFormat.format(rdv.getDateConsultation()),
                rdv.getPatient().getNom(),
                rdv.getPatient().getTelephone(),
                rdv.getCategorie().getDesignation(),
                rdv.getPrix() + " DH",
                rdv.getDescription(),
                rdv.getStatutPaiement() != null ? rdv.getStatutPaiement() : "Impayé"
            };
            model.addRow(row);
        }
        
        // Message de confirmation
        JOptionPane.showMessageDialog(this,
            tousRendezVous.size() + " rendez-vous chargés avec succès!",
            "Chargement réussi",
            JOptionPane.INFORMATION_MESSAGE);
            
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Erreur lors du chargement des rendez-vous: " + e.getMessage(),
            "Erreur",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionRdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionRdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionRdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionRdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionRdv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
