/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appmedicale;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
/**
 *
 * @author HP
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        ProgressBar.setVisible(false);
    }
    
    // Ajoutez cette méthode dans votre classe LoginFrame
private void showLoading(boolean show) {
    if (show) {
        btnconnecter.setEnabled(false);
        btnconnecter.setText("Connexion...");
        lbllLoading.setVisible(true);
        // Vous pouvez ajouter un GIF animé ici
    } else {
        btnconnecter.setEnabled(true);
        btnconnecter.setText("se connecter");
        lbllLoading.setVisible(false);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        juser = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jlogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jpassword = new javax.swing.JPasswordField();
        btnconnecter = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        lbllLoading = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");
        setSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\images.jpg")); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 240, 270));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 410));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(31, 153, 88));
        jLabel3.setText("            PAGE DE CONNEXION");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 280, 50));

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        jLabel1.setText("type utilisateur");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 120, -1));

        juser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        juser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MEDECIN", "ASSISTANT" }));
        jPanel1.add(juser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 130, -1));

        jLabel4.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        jLabel4.setText("login");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 40, -1));
        jPanel1.add(jlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 160, -1));

        jLabel5.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        jLabel5.setText("mot de passe");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        jPanel1.add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 160, -1));

        btnconnecter.setBackground(new java.awt.Color(31, 153, 88));
        btnconnecter.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnconnecter.setForeground(new java.awt.Color(255, 255, 255));
        btnconnecter.setText("se connecter");
        btnconnecter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconnecterActionPerformed(evt);
            }
        });
        jPanel1.add(btnconnecter, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 160, 30));

        jLabel7.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel7.setText(" Test: medecin/medecin123 ou assistante/assistante123");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        lbllLoading.setBackground(new java.awt.Color(31, 153, 88));
        jPanel1.add(lbllLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 160, 50));

        ProgressBar.setBackground(new java.awt.Color(31, 153, 88));
        jPanel1.add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 470, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconnecterActionPerformed
        String login = jlogin.getText().trim();
        String password = new String(jpassword.getPassword());
        String userType = (String) juser.getSelectedItem();
        
        // Validation des champs
        if (login.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(LoginFrame.this, 
                "Veuillez remplir tous les champs", 
                "Erreur", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Afficher le chargement
    btnconnecter.setEnabled(false);
    btnconnecter.setText("Connexion...");
    ProgressBar.setVisible(true);
    ProgressBar.setIndeterminate(true); // Animation de chargement
    lbllLoading.setVisible(true);
    lbllLoading.setText("Connexion en cours...");
        
         
        // Utiliser SwingWorker pour ne pas bloquer l'interface
    SwingWorker<Utilisateur, Void> worker = new SwingWorker<Utilisateur, Void>() {
        @Override
        protected Utilisateur doInBackground() throws Exception {
            String typeBDD = userType.equals("MEDECIN") ? "MEDECIN" : "ASSISTANT";
            UtilisateurDAO userDAO = new UtilisateurDAO();
            Utilisateur user = userDAO.authentifier(login, password);
            
            // Vérifier le type
            if (user != null && !user.getType().equals(typeBDD)) {
                return null;
            }
            return user;
        }
        
        @Override
        protected void done() {
            try {
                Utilisateur user = get();
                
                // Cacher le chargement
                ProgressBar.setVisible(false);
                lbllLoading.setVisible(false);
                btnconnecter.setEnabled(true);
                btnconnecter.setText("se connecter");
                
                if (user != null) {
                    // Connexion réussie
                    JOptionPane.showMessageDialog(LoginFrame.this, 
                        "Connexion réussie! Bienvenue " + user.getLogin(), 
                        "Succès", 
                        JOptionPane.INFORMATION_MESSAGE);
                    
                    LoginFrame.this.setVisible(false);
                    
                    if (user.isMedecin()) {
                        dispose();
                        new DashboardMedecin().setVisible(true);
                    } else {
                        dispose();
                        new DashboardAssistante().setVisible(true);
                    }
                } else {
                    // Échec de l'authentification
                    JOptionPane.showMessageDialog(LoginFrame.this, 
                        "Login, mot de passe ou type d'utilisateur incorrect", 
                        "Erreur d'authentification", 
                        JOptionPane.ERROR_MESSAGE);
                    jpassword.setText("");
                    jlogin.requestFocus();
                }
                
            } catch (Exception ex) {
                // Cacher le chargement en cas d'erreur
                ProgressBar.setVisible(false);
                lbllLoading.setVisible(false);
                btnconnecter.setEnabled(true);
                btnconnecter.setText("se connecter");
                
                JOptionPane.showMessageDialog(LoginFrame.this, 
                    "Erreur lors de la connexion: " + ex.getMessage(), 
                    "Erreur", 
                    JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    };
    
    worker.execute();
        
    }//GEN-LAST:event_btnconnecterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JToggleButton btnconnecter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jlogin;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JComboBox<String> juser;
    private javax.swing.JLabel lbllLoading;
    // End of variables declaration//GEN-END:variables
}
